### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by benjaminoakes** [TabCarousel/TabCarousel#73]
Follow [release process](https://github.com/TabCarousel/TabCarousel/wiki/Release-Process)

**Comment by benjaminoakes** [comment]
> **Your extension was submitted for review**
> 
> You may check the status on the developer dashboard home page.
> 
> Items staged to be published later will expire 30 days after they have passed review.

**Comment by benjaminoakes** [comment]
Version 1.0.2 is now "pending review" and should be released soon.  Once released, this issue can be closed.

Thank you so much for all your hard work on this, @Jimadine!  It's been a pleasure working with you.  :smile:

**Comment by Jimadine** [comment]
> Version 1.0.2 is now "pending review" and should be released soon. Once released, this issue can be closed.
> 
> Thank you so much for all your hard work on this, @Jimadine! It's been a pleasure working with you. 😄

You're very welcome :smiley:. It's good be able to give back to something we're actively using, and to learn new things along the way!

**Comment by benjaminoakes** [comment]
> It's good be able to give back to something we're actively using, and to learn new things along the way!

I'm very happy to see this comment. ❤️

It would be great to hear more about what you're doing with TabCarousel, if you'd like to share.  🙂

In any case, your contributions are always welcome. It's great to get pull requests from the user community. 😀

**Comment by benjaminoakes** [comment]
I see 1.0.2 listed on the public Chrome Web Store, so I'm closing this issue.  If anyone sees issues specific to the release of 1.0.2, please comment here.

**Comment by Jimadine** [comment]
@benjaminoakes - to share a bit about what I'm using TabCarousel for 😃. I work for a University in the UK, and part of my role is to help with the University Library's IT matters. In the Library buildings it's used to display signage images full screen (with Chrome's `--start-fullscreen` option) on very large TVs connected up to mini PCs. The images are stored in Google Drive. The beauty of this arrangement is that the Librarians who maintain/update the images on their own laptops can leverage Google Drive's rudimentary versioning so that they can upload a new image with the same filename as the original and the associated URL will stay the same. TabCarousel, with the Bypass Cache option enabled, will then pick up any changes to the image within 5 minutes (when a reload is performed).

The downside I found when I was originally testing TabCarousel was that the tab reload wasn't enough to refresh the images after they had changed. I tried adding the `--disk-cache-dir=nul` option to the Chrome command line, but it didn't help. But thankfully the work to add [a Bypass Cache option](https://github.com/TabCarousel/TabCarousel/commit/a72e03b1a4486047f1db3ee9729bfb4e75337d94) solved it (thank you, @madhur!).

Just to also mention that from [further reading](https://stackoverflow.com/questions/70684877/how-do-you-implement-a-frequent-timer-for-chrome-extension-with-manifest-version), it's sounding more & more like the [temporary fix](https://github.com/TabCarousel/TabCarousel/pull/70) for keeping the service worker alive might become permanent, unless of course one of you geniuses come up with a solution. However, I'll continue to read around / mull it over.

Finally, just in relation to 1.0.2, are you able to add the zip to [the Releases page](https://github.com/TabCarousel/TabCarousel/releases), as for the previous releases?

**Comment by benjaminoakes** [comment]
> to share a bit about what I'm using TabCarousel for 😃. I work for a University in the UK, and part of my role is to help with the University Library's IT matters. In the Library buildings it's used to display signage images full screen (with Chrome's --start-fullscreen option) on very large TVs connected up to mini PCs. The images are stored in Google Drive. The beauty of this arrangement is that the Librarians who maintain/update the images on their own laptops can leverage Google Drive's rudimentary versioning so that they can upload a new image with the same filename as the original and the associated URL will stay the same. TabCarousel, with the Bypass Cache option enabled, will then pick up any changes to the image within 5 minutes (when a reload is performed).

That's great.  :smile:  I'd love to see pictures sometime.

>The downside I found when I was originally testing TabCarousel was that the tab reload wasn't enough to refresh the images after they had changed. I tried adding the --disk-cache-dir=nul option to the Chrome command line, but it didn't help. But thankfully the work to add a Bypass Cache option solved it (thank you, @madhur!).

Agreed, thanks @madhur!

There are a number of outstanding issues like this that I typically haven't had the time to address.  Help is always appreciated from anyone willing to lend a hand.  :smile: 

> Just to also mention that from further reading, it's sounding more & more like the temporary fix for keeping the service worker alive might become permanent, unless of course one of you geniuses come up with a solution. However, I'll continue to read around / mull it over.

Good enough for now, I think :smile: 

>Finally, just in relation to 1.0.2, are you able to add the zip to [the Releases page](https://github.com/TabCarousel/TabCarousel/releases), as for the previous releases?

I created a release, which adds a zip of the tag automatically.

That said, there are quite a few places to update on each release, including the Chrome Web Store page.  We should attempt to consolidate this information so it's less labor-intensive to update.  Related: I would still like to have [a Firefox version someday](https://github.com/TabCarousel/TabCarousel/issues/68), which will add yet another manual release step.  :disappointed:
